'use strict';
const fs = require('fs');
module.exports = {
  DashboardIcon: 'Dashboard',
  DmaIcon: 'Map',
  AppUserIcon: 'AccountBox',
  PermissionIcon: 'Group',
  DesignSetupIcon: 'SettingsOverscan',
  ParentMenuMatIcon: 'Polymer',
  ManageMatIcon: 'InsertChart',
  StatisticMatInStkIcon: 'ViewList',
  StatisticMatByDmaIcon: 'ViewList',
  StatisticMatByLifeSpanIcon: 'ViewList',
  ExportStockIcon: 'Eject',
  PrintIcon: 'Print',
  AddMatTypeIcon: 'Add',
  MatDetailTypeIcon: 'ViewList',
  OtherIcon: 'Memory',
  StatisticButtonIcon: 'Transform',
  ParentMenuStatisticIcon: 'InsertChart',
  ConfigurationIcon: 'Settings',
  MonitoringIcon: 'Web',
  EmploymentIcon: 'InsertChart',
  TaskboardIcon: 'InsertChart',
  RestoreMatIcon: 'Error',
  ReturnMatForStockIcon: 'CompareArrows',
  ParentMenuReportIcon: 'ViewList',
  WaterLossIcon: 'FormatColorReset',
  QuantityIcon: 'Opacity',
  PressureIcon: 'NetworkCheck',
  FlowRateIcon: 'BubbleChart',
  StatusIcon: 'Timeline',
  WaterFlowPressureIcon: 'LowPriority',
  LogTimeIcon: 'AccessTime',
  MaterialOnMapIcon: 'BubbleChart',
  FilterIcon: 'FilterIcon',
  FlowLoggerIcon: 'SettingsRemote',
  MeterIcon: { data: fs.readFileSync(`${__dirname}/svgs/meter-icon.svg`, 'utf8') },
  NodeIcon: 'Adjust',
  PipeIcon: 'Crop75',
  PressureReducingIcon: 'ConfirmationNumber',
  PumpIcon: { data: fs.readFileSync(`${__dirname}/svgs/pump-icon.svg`, 'utf8') },
  QualityLoggerIcon: { data: fs.readFileSync(`${__dirname}/svgs/quality-logger-icon.svg`, 'utf8') },
  TankIcon: { data: fs.readFileSync(`${__dirname}/svgs/tank-icon.svg`, 'utf8') },
  ValveIcon: { data: fs.readFileSync(`${__dirname}/svgs/valve-icon.svg`, 'utf8') },
  DropIcon: { data: fs.readFileSync(`${__dirname}/svgs/drop-icon.svg`, 'utf8') },
  WaterSourceIcon: { data: fs.readFileSync(`${__dirname}/svgs/water-source-icon.svg`, 'utf8') },
  FactoryIcon: 'LocationCity',
};
