cache:
  paths:
    - node_modules/
  key: '${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}'

variables:
  CONTAINER_REGISTRY: gitlab.Bworks.online:5050/setfil/water/water_api:v0.1.1

stages:
  - build
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - mkdir --parents ~/.ssh
  - chmod 600 packages/water-api/ssh/id_rsa
  - ssh-add packages/water-api/ssh/id_rsa
  - ssh-keyscan gitlab.Bworks.online >> ~/.ssh/known_hosts
  - if [[ -f ./.dockerenv ]]; then echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config; fi
  - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN gitlab.Bworks.online:5050

build:
  stage: build
  tags:
    - r01
  script:
    - pwd
    - export NODE_DEFAULT_LANGUAGE=vi
    - export NODE_ACTIVE_LANGUAGES=vi,en
    - yarn --force
    - yarn build-ctm
    - yarn build-nms
    - yarn build-org
    - yarn build-src
    - yarn build-login
    - yarn build-client
    - docker build --tag $CONTAINER_REGISTRY .
    - docker push $CONTAINER_REGISTRY
    - docker rmi $CONTAINER_REGISTRY
    - docker system prune --force
  artifacts:
    paths:
      - ./packages/water-api/client/ctm
      - ./packages/water-api/client/client
      - ./packages/water-api/client/nms
      - ./packages/water-api/client/org
      - ./packages/water-api/client/src
      - ./packages/water-api/client/cmn
    expire_in: 1 week
  only:
    - master

deploy_first_time:
  stage: deploy
  tags:
    - r01
  script:
    - pwd && ls -l
    - make create-new-env
  when: manual
  only:
    - master

deploy:
  stage: deploy
  tags:
    - r01
  script:
    - pwd && ls -l
    - make deploy-new-build
  when: manual
  only:
    - master

deploy_bac_ninh:
  stage: deploy
  tags:
    - r01
  script:
    - pwd && ls -l
    - make deploy-new-build
  when: manual
  only:
    - bacninh
