export default [
  'appusers',
  'interfacestandards',
  'waterparameters',
  'waterstandards',
  'measuremethods',
  'dataloggers',
  'meters',
  'sensors',
  'sensorprobes',
  'watersources',
  'pumps',
  'watersourcegroups',
  'srcconfigs',
];
