module.exports = [
  // Default ACLs for client user in wctm-client
  {
    model: 'WaterSource',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'WaterParameter',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'WaterSourceGroup',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'MessageSystem',
    property: 'count',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'MeterNumberSubmit',
    property: 'postSubmit',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'MeterNumberSubmit',
    property: 'checkIfHavePrivilegeSubmit',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'MeterNumberSubmit',
    property: 'getDefaultStatus',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Client',
    property: 'getInfoWaterUsage',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientMeterNumber',
    property: 'payInvoice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Client',
    property: 'getInfoWaterPressure',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientMeterNumber',
    property: 'getLastWritedMonth',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Client',
    property: 'getInfoQualityWater',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Client',
    property: 'getAlertQualityWater',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Client',
    property: 'getAlertWaterUsage',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Client',
    property: 'getAlertWaterPressure',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'TicketSupport',
    property: 'getSecuredTicketSupport',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientUser',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientUser',
    property: 'getClientInfo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientUser',
    property: 'registerDevice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientUser',
    property: 'changeClientSettings',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'TicketType',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'TicketSupport',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'AppUser',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'TicketPriority',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Announcement',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Announcement',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Dma',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'AnnouncementType',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'AnnouncementPriority',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'Client',
    property: 'getInfoClientLogin',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientUser',
    property: 'change-password',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'TicketBody',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'TicketBody',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'TicketSupport',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientUser',
    property: 'setPasswordToNewAccount',
    accessType: 'EXECUTE',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientUser',
    property: 'resetUserPassword',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: '$unauthenticated',
  },
  // Default ACLs for admin and recorder in wctm-web
  {
    model: 'AppUser',
    property: 'changePassword',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeter',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoDistrict',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoCountry',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoWard',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoProvince',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoProvince',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoDistrict',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoWard',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoQuarter',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoQuarter',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoGroup',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientMeterNumber',
    property: 'getInvoiceDetail',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientMeterNumber',
    property: 'getInvoiceData',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientMeterNumber',
    property: 'payInvoiceInApp',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'client',
  },
  {
    model: 'ClientMeterNumber',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'payInvoice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeter',
    property: 'updateQrCode',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'InstallationTeam',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRequest',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRequest',
    property: 'completeRequest',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'InstallationTeam',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoGroup',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'offlineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'offlineUpload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'offlineUpload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'updateMonth',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoCountry',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoQuarter',
    property: 'offlineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'getClientApp',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'getDefaultNewMonth',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'invoiceOfflineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'getClientMeterNumberApp',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'widgetRevenue',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRequest',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'statisticRevenue',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'status',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'widgetWaterQuantity',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'statisticQuantityWater',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRegister',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'statisticClientWriteWater',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Formula',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'offlineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'contractSign',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'WaterProvider',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'WaterProvider',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'getClientInvoiceApp',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRegister',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Dma',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRegister',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'widgetWaterLoss',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Formula',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeter',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmConfig',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRegister',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'RootMeter',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ExcelUtils',
    property: 'exportExcelFile',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeter',
    property: 'editClientMeter',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'editClient',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeter',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterHistory',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Dma',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'fillZeroVolume',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRequest',
    property: '__get__client',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeter',
    property: 'setupNewMeter',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'writeNewMonth',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'importClientMeterNumbersFromExcel',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmFile',
    property: 'download',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'EInvoiceRange',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'RootMeter',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'delete',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'invoiceLockList',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ExcelFile',
    property: 'upload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientRequest',
    property: 'replaceMeterRequest',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'exportExcelByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'fillTemplateForBulkWriting',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'shouldReplaceEinvoice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'EInvoiceData',
    property: 'getLatestEinvoice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'joinWithMeterNumber',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'forceUpdateMonth',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'exportInvoices',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'EInvoiceData',
    property: 'getEInvoiceDraftPreview',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'EInvoiceData',
    property: 'createNewEInvoice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'stops',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'EInvoiceData',
    property: 'downloadEinvoice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'getClientByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'calculateInvoices',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'countClientStatusByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'exportExcelInvoiceSummaryGroupByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'reportDebtClientByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'exportExcelTermNumberGroupByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'PDFGetter',
    property: 'getPDF',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'reportQuantityClientByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'reportDebtClientByProvider',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ExcelUtils',
    property: 'getWaterStationData',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmReport',
    property: 'exportReport',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'resumes',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoWard',
    property: 'validateExistenceOfGeoGroupSchema',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ExcelUtils',
    property: 'exportWaterStationReport',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientUser',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmTemplate',
    property: 'exportWaterStationReportResult',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'ClientMeterNumber',
    property: 'exportExcelTermNumberSummaryGroupByGeo',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketBody',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketType',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketPriority',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketSupport',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'reportQuantityClientByProvider',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Announcement',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketBody',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketSupport',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AnnouncementPriority',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketSupport',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Announcement',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Announcement',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Announcement',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmCompany',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'TicketSupport',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmCompany',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmCompany',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'WaterProvider',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmCompany',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AnnouncementType',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'WaterProvider',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'InstallationTeam',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'InstallationTeam',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'WaterProvider',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmCompany',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoCountry',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoProvince',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoProvince',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoCountry',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'CtmCompany',
    property: 'doActive',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoDistrict',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoWard',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoDistrict',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoDistrict',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'InstallationTeam',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'getRolesByAppUserId',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoQuarter',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoQuarter',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoWard',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoProvince',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'saveAppUser',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Role',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'banUser',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoWard',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Role',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Role',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Role',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'GeoQuarter',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Formula',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'PackageConfig',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'setAccessForRole',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'getPathsByRoleAndProject',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'AppUser',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'QuotaWater',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'RootMeter',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'QuotaWater',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Formula',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Role',
    property: 'isDeletable',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'RootMeter',
    property: 'create',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'getClientByPay',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'RootMeter',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'getClientByWrite',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Formula',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'countClientByPay',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'QuotaWater',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },
  {
    model: 'Client',
    property: 'countClientByWrite',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-admin',
  },

  {
    model: 'AppUser',
    property: 'changePassword',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeter',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoDistrict',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoWard',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoProvince',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoCountry',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoDistrict',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoQuarter',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoWard',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoQuarter',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoGroup',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeter',
    property: 'updateQrCode',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'InstallationTeam',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoGroup',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoProvince',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'payInvoice',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'InstallationTeam',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'offlineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoCountry',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientRequest',
    property: 'completeRequest',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'GeoQuarter',
    property: 'offlineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'updateMonth',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'offlineUpload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'getDefaultNewMonth',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientRequest',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeter',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'invoiceOfflineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'offlineUpload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'getClientApp',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientRequest',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'status',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeter',
    property: 'editClientMeter',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'getClientMeterNumberApp',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeter',
    property: 'replaceById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeter',
    property: 'setupNewMeter',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'offlineDownload',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'deleteById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'RootMeter',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientRegister',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterNumber',
    property: 'delete',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'getClientInvoiceApp',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientRequest',
    property: 'replaceMeterRequest',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'RootMeter',
    property: 'findById',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'stops',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'ClientMeterHistory',
    property: 'find',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
  {
    model: 'Client',
    property: 'resumes',
    accessType: '*',
    permission: 'ALLOW',
    principalType: 'ROLE',
    principalId: 'ctm-recorder',
  },
];
