import { EmployeeAppIcon } from '../styles/Icons';
export default {
  name: 'employeeSmartPhone',
  label: 'generic.pages.employeeSmartPhone',
  icon: EmployeeAppIcon,
  url: 'employeeSmartPhone',
  resources: [
    'clientregisters',
    'clientmeters',
    'clientmeternumbers',
    'clients',
    'waterproviders',
    'dmas',
    'geodistricts',
    'geowards',
    'geoquarters',
    'geoprovinces',
    'messagesystems',
  ],
  screens: ['writeMeterNumber', 'ClientInvoice', 'clients', 'ClientRequest', 'offlineSync', 'settings'],
  active: false,
  access: {
    clients: {
      apis: [
        { url: '/Clients', method: 'get' },
        { url: '/Clients/{id}', method: 'get' },
        { url: '/Clients/getClientApp', method: 'get' },
        { url: '/Clients/{id}', method: 'put' },
        { url: '/ClientMeters/updateQrCode', method: 'post' },
        { url: '/ClientMeters/{id}', method: 'get' },
        { url: '/ClientMeters', method: 'get' },
        { url: '/ClientRegisters/getClientRegisterApp', method: 'get' },
        { url: '/ClientRegisters/{id}', method: 'get' },
        { url: '/ClientRegisters/{id}', method: 'put' },
      ],
    },
    writeMeterNumber: {
      apis: [
        { url: '/Clients/getClientMeterNumberApp', method: 'get' },
        { url: '/ClientMeterNumbers/updateMonth', method: 'post' },
        { url: '/ClientMeterNumbers', method: 'get' },
        { url: '/ClientMeterNumbers/{id}', method: 'get' },
        { url: '/ClientMeterNumbers/getDefaultNewMonth/{id}/{yearMonth}', method: 'get' },
      ],
    },
    ClientInvoice: {
      apis: [
        { url: '/Clients/getClientInvoiceApp', method: 'get' },
        { url: '/ClientMeterNumbers/payInvoiceByEmployee', method: 'post' },
      ],
    },
    ClientRequest: {
      apis: [
        { url: '/ClientRequests', method: 'get' },
        { url: '/ClientRequests/{id}', method: 'get' },
        { url: '/ClientRequests/completeRequest', method: 'post' },
      ],
    },
    offlineSync: {
      apis: [
        { url: '/Clients/offlineDownload', method: 'post' },
        { url: '/GeoQuarters/offlineDownload', method: 'post' },
        { url: '/ClientMeterNumbers/offlineDownload', method: 'post' },
        { url: '/Clients/offlineUpload', method: 'post' },
        { url: '/ClientMeterNumbers/offlineUpload', method: 'post' },
        { url: '/Clients/invoiceOfflineDownload', method: 'post' },
      ],
    },
    common: {
      apis: [
        { url: '/AppUsers/registerDevice', method: 'post' },
        { url: '/GeoQuarters', method: 'get' },
        { url: '/GeoWards', method: 'get' },
        { url: '/GeoDistricts', method: 'get' },
        { url: '/GeoProvinces', method: 'get' },
        { url: '/GeoCountries', method: 'get' },
        { url: '/GeoGroups', method: 'get' },
        { url: '/GeoQuarters/{id}', method: 'get' },
        { url: '/GeoWards/{id}', method: 'get' },
        { url: '/GeoDistricts/{id}', method: 'get' },
        { url: '/GeoProvinces/{id}', method: 'get' },
        { url: '/GeoCountries/{id}', method: 'get' },
        { url: '/GeoGroups/{id}', method: 'get' },
        { url: '/MessageSystems', method: 'get' },
        { url: '/MessageSystems/count', method: 'get' },
        { url: '/MessageSystems/updateClientReceived', method: 'get' },
        { url: '/PackageConfigs/registerMenu', method: 'post' },
        { url: '/InstallationTeams', method: 'get' },
        { url: '/InstallationTeams/{id}', method: 'get' },
      ],
    },
    settings: {
      list: true,
      apis: [{ url: '/appusers/change-password', method: 'post' }],
    },
    // view: {
    //   apis: [
    //     { url: '/AppUsers/registerDevice', method: 'post' },
    //     { url: '/Clients', method: 'get' },
    //     { url: '/Clients/{id}', method: 'get' },
    //     { url: '/Clients/{id}', method: 'put' },
    //     { url: '/ClientMeters', method: 'get' },
    //     { url: '/GeoQuarters', method: 'get' },
    //     { url: '/GeoWards', method: 'get' },
    //     { url: '/GeoDistricts', method: 'get' },
    //     { url: '/GeoProvinces', method: 'get' },
    //     { url: '/GeoCountries', method: 'get' },
    //     { url: '/GeoGroups', method: 'get' },
    //     { url: '/GeoQuarters/{id}', method: 'get' },
    //     { url: '/GeoWards/{id}', method: 'get' },
    //     { url: '/GeoDistricts/{id}', method: 'get' },
    //     { url: '/GeoProvinces/{id}', method: 'get' },
    //     { url: '/GeoCountries/{id}', method: 'get' },
    //     { url: '/GeoGroups/{id}', method: 'get' },
    //     { url: '/ClientMeters/updateQrCode', method: 'post' },
    //     { url: '/ClientMeterNumbers', method: 'get' },
    //     { url: '/ClientMeterNumbers/{id}', method: 'get' },
    //     { url: '/ClientMeterNumbers/getDefaultNewMonth/{id}/{yearMonth}', method: 'get' },
    //     { url: '/ClientMeterNumbers/payInvoiceByEmployee', method: 'post' },
    //     { url: '/InstallationTeams', method: 'get' },
    //     { url: '/InstallationTeams/{id}', method: 'get' },
    //     { url: '/ClientRequests', method: 'get' },
    //     { url: '/ClientRequests/{id}', method: 'get' },
    //     { url: '/ClientRequests/completeRequest', method: 'post' },
    //     { url: '/ClientMeterNumbers/updateMonth', method: 'post' },
    //     { url: '/ClientMeterNumbers/offlineDownload', method: 'post' },
    //     { url: '/ClientMeterNumbers/offlineUpload', method: 'post' },
    //     { url: '/Clients/offlineDownload', method: 'post' },
    //     { url: '/Clients/offlineUpload', method: 'post' },
    //     { url: '/Clients/invoiceOfflineDownload', method: 'post' },
    //     { url: '/GeoQuarters/offlineDownload', method: 'post' },
    //     { url: '/Clients/getClientMeterNumberApp', method: 'get' },
    //     { url: '/Clients/getClientInvoiceApp', method: 'get' },
    //     { url: '/Clients/getClientApp', method: 'get' },
    //     { url: '/ClientRegisters/getClientRegisterApp', method: 'get' },
    //     { url: '/MessageSystems', method: 'get' },
    //     { url: '/MessageSystems/count', method: 'get' },
    //     { url: '/MessageSystems/updateClientReceived', method: 'get' },
    //     { url: '/PackageConfigs/registerMenu', method: 'post' },
    //   ],
    // },
  },
};
