module.exports = [
  {
    id: 'ctm',
    data: {
      Dashboard: true,
      ParentMenuClient: true,
      clientRegister: true,
      clientContract: true,
      clientMeter: true,
      clientRequest: true,
      client: true,
      Business: true,
      clientMeterNumber: true,
      invoiceLock: true,
      invoiceExport: true,
      clientDebt: true,
      invoiceHistory: true,
      trackWriteWaterClient: true,
      printInvoiceByGeo: true,
      EInvoiceRange: true,
      ParentMenuMap: true,
      clientDistributionMap: true,
      clientWriteMap: true,
      clientPayMap: true,
      clientFormat: true,
      Report: true,
      reportTermNumberGroupByGeo: true,
      reportInvoiceSummaryGroupByGeo: true,
      reportTermNumberSummaryGroupByGeo: true,
      reportIncome: true,
      reportRevenueLossWater: true,
      reportRevenueLossClient: true,
      reportDebtClient: true,
      reportQuantityClient: true,
      reportClientMeter: true,
      reportWaterStationReport: true,
      EInvoiceData: true,
      reportEInvoice: true,
      ClientCommunication: true,
      TicketSupport: true,
      TicketPriority: true,
      Announcement: true,
      Enterprise: true,
      CtmCompany: true,
      Partner: true,
      InstallationTeam: true,
      Geo: true,
      GeoCountry: true,
      GeoProvince: true,
      GeoDistrict: true,
      GeoWard: true,
      GeoQuarter: true,
      ImportGeo: true,
      ImportGeoGroup: true,
      Permission: true,
      appuser: true,
      role: true,
      rolePermission: true,
      Taskboard: true,
      Setting: true,
      formula: true,
      QuotaWater: true,
      RootMeter: true,
      CtmTemplate: true,
      Configuration: true,
      changePassword: true,
      clientUserRequest: true,
      employeeSmartPhone: true,
    },
  },
  {
    id: 'app-ctm',
    data: {
      menu: [
        {
          name: 'Main',
          label: 'generic.pages.main',
          icon: 'home',
          url: '/',
          screens: {},
          resources: ['clients'],
          active: false,
          access: { read: [], write: [] },
        },
        {
          name: 'writeMeterNumber',
          label: 'generic.pages.writeMeterNumber',
          icon: 'md-clipboard',
          url: '/meterNumber',
          screens: {
            editClientMeterNumber: { subPath: ':previousPage/:id' },
            createWithMonth: { subPath: ':previousPage/:clientId/:month' },
            qrScan: { subPath: ':termMonth' },
          },
          resources: [
            'clientaliasmeternumbers',
            'clientmeternumber',
            'clientmeters',
            'geodistricts',
            'geoward',
            'geoquarters',
          ],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'ClientInvoice',
          label: 'generic.pages.clientInvoice',
          icon: 'md-paper',
          url: '/clientInvoice',
          screens: { invoiceDetail: { subPath: ':previousPage/:id' }, qrScan: { subPath: ':termMonth' } },
          resources: ['clientaliasinvoices', 'geoquarters', 'geowards', 'geodistricts'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'clients',
          label: 'generic.pages.clients',
          icon: 'md-people',
          url: '/clients',
          screens: {
            mapView: { subPath: ':filterValues' },
            mapViewRegister: { subPath: ':filterValues' },
            clientEdit: { subPath: ':previousPage/:id' },
            clientRegisterEdit: { subPath: ':previousPage/:id' },
            qrScan: { subPath: ':termMonth' },
          },
          resources: ['clients', 'geoquarters', 'geowards', 'geodistricts', 'clientregisters'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'ClientRequest',
          label: 'generic.pages.clientRequest',
          icon: 'md-build',
          url: '/clientRequest',
          screens: {},
          resources: ['clientaliasclientrequests', 'clients', 'clientrequests', 'installationteams'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'offlineSync',
          label: 'generic.pages.offlineSync.main',
          icon: 'md-sync',
          url: '/offlineSync',
          offline: true,
          screens: {},
          resources: ['offlinemeternumbersaliasupload', 'offlineclientsaliasupload', 'offlineinvoicealiasupload'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'offlineWriteMeterNumber',
          label: 'generic.pages.offlineWriteMeterNumber',
          icon: 'md-clipboard',
          url: '/offlineMeterNumber',
          offline: true,
          screens: { writeMeter: { subPath: ':previousPage/:id' } },
          resources: ['offlinemeternumbers'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'OfflineInvoice',
          label: 'generic.pages.offlineInvoice',
          icon: 'md-paper',
          url: '/offlineInvoice',
          screens: { invoiceDetail: { subPath: ':previousPage/:id' } },
          resources: ['offlineinvoices'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'offlineClient',
          label: 'generic.pages.offlineClient',
          icon: 'md-people',
          url: '/offlineClient',
          offline: true,
          screens: { offlineClientEdit: { subPath: ':previousPage/:id' } },
          resources: ['offlineclients'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'account',
          label: 'generic.pages.settings',
          icon: 'md-settings',
          url: '/settings',
          screens: {},
          resources: ['appusers'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'notifications',
          label: 'generic.pages.notifications',
          icon: 'md-notifications',
          url: '/notifications',
          screens: {},
          resources: ['messagesystems'],
          active: false,
          access: { read: [], write: [] },
        },
      ],
      defaultMenu: [
        {
          name: 'Main',
          label: 'generic.pages.main',
          icon: { key: null, ref: null, props: { name: 'home' }, _owner: null, _store: {} },
          url: '/',
          screens: {},
          resources: ['clients'],
          active: false,
          access: { read: [], write: [] },
        },
        {
          name: 'account',
          label: 'generic.pages.settings',
          icon: { key: null, ref: null, props: { name: 'md-settings' }, _owner: null, _store: {} },
          url: '/settings',
          screens: {},
          resources: ['appusers'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'notifications',
          label: 'generic.pages.notifications',
          icon: { key: null, ref: null, props: { name: 'md-notifications' }, _owner: null, _store: {} },
          url: '/notifications',
          screens: {},
          resources: ['messagesystems'],
          active: false,
          access: { read: [], write: [] },
        },
      ],
      dependentMenu: {
        offlineSync: [
          {
            name: 'offlineWriteMeterNumber',
            label: 'generic.pages.offlineWriteMeterNumber',
            icon: {
              key: null,
              ref: null,
              props: { name: 'md-clipboard', style: { color: '#a0a0a0' } },
              _owner: null,
              _store: {},
            },
            url: '/offlineMeterNumber',
            offline: true,
            screens: { writeMeter: { subPath: ':previousPage/:id' } },
            resources: ['offlinemeternumbers'],
            active: true,
            access: { read: [], write: [] },
          },
          {
            name: 'OfflineInvoice',
            label: 'generic.pages.offlineInvoice',
            icon: {
              key: null,
              ref: null,
              props: { name: 'md-paper', style: { color: '#a0a0a0' } },
              _owner: null,
              _store: {},
            },
            url: '/offlineInvoice',
            screens: { invoiceDetail: { subPath: ':previousPage/:id' } },
            resources: ['offlineinvoices'],
            active: true,
            access: { read: [], write: [] },
          },
          {
            name: 'offlineClient',
            label: 'generic.pages.offlineClient',
            icon: {
              key: null,
              ref: null,
              props: { name: 'md-people', style: { color: '#a0a0a0' } },
              _owner: null,
              _store: {},
            },
            url: '/offlineClient',
            offline: true,
            screens: { offlineClientEdit: { subPath: ':previousPage/:id' } },
            resources: ['offlineclients'],
            active: true,
            access: { read: [], write: [] },
          },
        ],
      },
      offlineMenu: [
        {
          name: 'offlineWriteMeterNumber',
          label: 'generic.pages.offlineWriteMeterNumber',
          icon: {
            key: null,
            ref: null,
            props: { name: 'md-clipboard', style: { color: '#a0a0a0' } },
            _owner: null,
            _store: {},
          },
          url: '/offlineMeterNumber',
          offline: true,
          screens: { writeMeter: { subPath: ':previousPage/:id' } },
          resources: ['offlinemeternumbers'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'OfflineInvoice',
          label: 'generic.pages.offlineInvoice',
          icon: {
            key: null,
            ref: null,
            props: { name: 'md-paper', style: { color: '#a0a0a0' } },
            _owner: null,
            _store: {},
          },
          url: '/offlineInvoice',
          screens: { invoiceDetail: { subPath: ':previousPage/:id' } },
          resources: ['offlineinvoices'],
          active: true,
          access: { read: [], write: [] },
        },
        {
          name: 'offlineClient',
          label: 'generic.pages.offlineClient',
          icon: {
            key: null,
            ref: null,
            props: { name: 'md-people', style: { color: '#a0a0a0' } },
            _owner: null,
            _store: {},
          },
          url: '/offlineClient',
          offline: true,
          screens: { offlineClientEdit: { subPath: ':previousPage/:id' } },
          resources: ['offlineclients'],
          active: true,
          access: { read: [], write: [] },
        },
      ],
      logo: 14,
      version: '1.1.4',
      projectKey: 'app-ctm',
      parentProjectKey: 'ctm',
    },
  },
  { id: 'nms', data: {} },
];
