module.exports = [
  { id: '1a1a1a1a1a1a1a1a1a1a1000', name: 'master' },
  {
    id: '1a1a1a1a1a1a1a1a1a1a1003',
    name: 'ctm-recorder',
    project: 'ctm',
    title: 'Nhân viên Ghi thu',
    default: true,
    menu: {
      Dashboard: { customer: true },
      employeeSmartPhone: { view: true },
      clientMeter: { view: true, edit: true, changeMeter: true, showHistory: true },
      clientRequest: { view: true, showHistory: true },
      clientMeterNumber: { historyWater: true, delete: true },
      clientDebt: { list: true, historyDebt: true, stop: true, resume: true },
      invoiceHistory: { list: true, historyInvoice: true },
      changePassword: { view: true },
      client: { view: true },
    },
  },
  {
    id: '1a1a1a1a1a1a1a1a1a1a1002',
    name: 'ctm-admin',
    project: 'ctm',
    title: 'Admin',
    default: true,
    menu: {
      Dashboard: {
        customer: true,
        revenue: true,
        waterQuantity: true,
        waterLoss: true,
        statisticRevenue: true,
        statisticPayment: true,
        statisticClientWriteWater: true,
        statisticQuantityWater: true,
      },
      clientRegister: { view: true, export: true, contract: true, create: true, edit: true },
      clientContract: { view: true, export: true, edit: true },
      clientMeter: { view: true, export: true, edit: true, changeMeter: true, showHistory: true },
      clientRequest: { view: true, export: true, completeRequest: true, showHistory: true },
      client: { view: true, export: true, edit: true },
      clientMeterNumber: {
        list: true,
        fillZeroTerm: true,
        editWriteWater: true,
        forceEditWriteWater: true,
        historyWater: true,
        delete: true,
        exportTemplate: true,
      },
      invoiceLock: { list: true, lock: true },
      invoiceExport: { list: true, printInvoice: true, payInvoice: true, exportEinvoice: true, exportExcel: true },
      clientDebt: { list: true, historyDebt: true, stop: true, resume: true },
      invoiceHistory: { list: true, historyInvoice: true },
      trackWriteWaterClient: { view: true },
      clientDistributionMap: { view: true },
      clientWritePayMap: { view: true },
      reportTermNumberGroupByGeo: { viewReportTermNumberGroupByGeo: true },
      reportInvoiceSummaryGroupByGeo: { viewReportInvoiceSummaryGroupByGeo: true },
      reportTermNumberSummaryGroupByGeo: { viewReportTermNumberSummaryGroupByGeo: true },
      reportDebtClient: {
        viewDebtClientByGeo: true,
        viewDebtClientByProvider: true,
        exportDebtClientByGeoAsPDF: true,
        exportDebtClientByProviderAsPDF: true,
      },
      reportQuantityClient: {
        viewQuantityClientByGeo: true,
        viewQuantityClientByProvider: true,
        exportQuantityClientByGeoAsPDF: true,
        exportQuantityClientByProviderAsPDF: true,
      },
      reportWaterStationReport: { view: true, exportPDF: true, exportExcel: true },
      TicketSupport: { view: true, edit: true, create: true, examine: true, answer: true },
      Announcement: { view: true, edit: true, create: true, examine: true },
      CtmCompany: { view: true, edit: true, delete: true, create: true, examine: true, activate: true },
      Partner: { view: true, edit: true, delete: true, create: true, examine: true },
      InstallationTeam: { view: true, edit: true, delete: true, create: true, examine: true },
      GeoCountry: { view: true, edit: true, delete: true, create: true, examine: true },
      GeoProvince: { view: true, edit: true, delete: true, create: true, examine: true },
      GeoDistrict: { view: true, edit: true, delete: true, create: true, examine: true },
      GeoWard: { view: true, edit: true, delete: true, create: true, examine: true },
      GeoQuarter: { view: true, edit: true, delete: true, create: true, examine: true },
      appuser: { view: true, ban: true, edit: true, create: true, delete: true },
      role: { view: true, edit: true, delete: true, create: true },
      rolePermission: { view: true, save: true },
      formula: { view: true, edit: true, create: true, delete: true },
      QuotaWater: { view: true, edit: true, examine: true },
      RootMeter: { view: true, edit: true, delete: true, create: true, examine: true },
      Configuration: { view: true },
      changePassword: { view: true },
      employeeSmartPhone: { view: true },
      clientWriteMap: { view: true },
      clientPayMap: { view: true },
      clientUserRequest: { view: true, approve: true, delete: true },
    },
  },
  // For wctm-client
  { id: '1a1a1a1a1a1a1a1a1a1a1001', name: 'client' },
  // collection: Role
  {
    id: '5d8dc80b596d0811bed514be',
    name: 'nms-test-nms',
    project: 'nms',
    title: 'test nms',
    menu: {
      Dashboard: {
        quantity: true,
        flowLogger: true,
        waterLoss: true,
        factory: true,
        currentStatus: true,
      },
      MapWaterLoss: {
        view: true,
      },
      MaterialOnMap: {
        view: true,
      },
      StatisticMatInStk: {
        view: true,
      },
      StatisticMatByDma: {
        view: true,
      },
      StatisticMatByLifeSpan: {
        view: true,
      },
      WaterLoss: {
        view: true,
      },
      WaterFlowPressure: {
        view: true,
      },
      MatDetailType: {
        create: true,
        edit: true,
        delete: true,
      },
      ManageMat: {
        importStock: true,
        exportStock: true,
        editStock: true,
        deleteStock: true,
        returnMat: true,
        deleteMatExport: true,
      },
      Design: {
        view: true,
        create: true,
        edit: true,
        delete: true,
      },
      InputKml: {
        import: true,
        edit: true,
        delete: true,
      },
      WaterMaintenance: {
        create: true,
        edit: true,
        delete: true,
      },
      Appuser: {
        view: true,
        ban: true,
        edit: true,
        create: true,
        delete: true,
      },
      Role: {
        view: true,
        edit: true,
        delete: true,
        create: true,
      },
      RolePermission: {
        view: true,
        save: true,
      },
      Configuration: {
        create: true,
        edit: true,
        delete: true,
      },
      Taskboard: {
        view: true,
        show: true,
        create: true,
        edit: true,
        delete: true,
      },
      changePassword: {
        view: true,
      },
      employeeSmartPhone: {
        view: true,
      },
    },
  },
];
